### ISSUE TITLE
Align contributor roles with standards

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#215]
The schema for Zenodo (see https://zenodo.org/schemas/records/record-v1.0.0.json) has a standard list of roles for contributors, including those listed below. We should align our roles with theirs. This will ease transition to publication:

```
            "ContactPerson",
            "DataCollector",
            "DataCurator",
            "DataManager",
            "Distributor",
            "Editor",
            "HostingInstitution",
            "Other",
            "Producer",
            "ProjectLeader",
            "ProjectManager",
            "ProjectMember",
            "RegistrationAgency",
            "RegistrationAuthority",
            "RelatedPerson",
            "Researcher",
            "ResearchGroup",
            "RightsHolder",
            "Sponsor",
            "Supervisor",
            "WorkPackageLeader"
```

WDYT @ehwenk ?

**Comment by ehwenk** [comment]
Coming back to this after two years, I think this is still needed.

I noticed that in the definitions files, "contributor" is still defined as, “Person responsible for entering data into AusTraits”, yet throughout metadata files it has been the “Person contributing the data to AusTraits” – we’ve talked about editing this several times and never done that.

I am not sure that aligning with Zenodo is going to exactly meet our needs, as the way we want to "group" and "split" people in the metadata files doesn't match with how we've entered their names into Zenodo.

For instance, we have split Zenodo's "DataCollector" into "collector" and "assistant". And other terms of ours do not map well onto the terms allowed for the Zenodo repository. I think the terms in AusTraits are mostly quite clear and functional, except we should use "contact" to designate the person who contributed data to AusTraits (or rename this "contributor") and devise a separate term for designate the data entry person (maybe a variant of "AusTraits_dataset_curator")

**Comment by ehwenk** [comment]
Suggestions from Melanie Barlow at ARDC include:

https://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml
https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf
https://documentation.ardc.edu.au/display/DOC/Related+objects+and+relationships#Relatedobjectsandrelationships-Relationattributes (Collection-Party relation)

I'll look into these and provide suggested changes.

**Comment by ehwenk** [comment]
Our current definitions in AusTraits:
            collector: The person (people) leading data collection (generally 1-2 people)
            contributor: Person responsible for entering data into AusTraits
            lab_leader: Leader of lab group at time of collection
            assistant: Anyone else who assisted in collection of the data
            contact: The person to contact with questions about the data set

The ARDC links aren't really the sort of categories we're looking for.

I've compiled lists for the `iso-19115` (geospatial data contributor standards) and `datacite.org` (what Zenodo uses) and it seems that `datacite.org` probably does provide the best matches. 

I think it would be good if the people added as a `DataCollector` in Zenodo were also designated as such in the AusTraits files, and then we can use some of the other roles to designate roles beyond being a `DataCollector`

See the GoogleSheets in austraits > austraits.build > data structure reviews for files that include all official desginations for the roles under both schemes

In summary: 

Role
--
DataManager = AusTraits person who handles data - although I think this could be included elsewhere in the metadata file, not under people; probably under config realistically, or at the very bottom of the metadata file
DataCollector = for all people involved in data collection and whose names will appear on Zenodo under `DataCollector`; includes both assistants and collectors per old vocab
ContactPerson = the person to contact; who email we have on file
ProjectLeader = head data collector - person who led project; generally the first author on the resulting publication
ProjectManager = head of lab (old "lab_leader" designation)
ProjectMember = other data collectors who were previously the "collectors" to whom we offered authorship; this parallels, at a different scale, who we've listed as `ProjectMember` for the overall AusTraits project on Zenodo

**Comment by ehwenk** [comment]
Following our meeting yesterday, we've decided to revise the people section of the metadata file, to separately list collectors (all people offered authorship on data papers, all people designated as "collectors" on Zenodo - this will merge together the previous "collector" and "lab leader" sections.

Note that in this section, people's names will be split into "last_name" and "given_name" fields.

This is followed by "contact", listing the person to contact - either the author, the person who sent the data to AusTraits, or a person within the broad AusTraits team who is storing the data.

"Curator" is the AusTraits team member who entered the study

"Assistants" are others to acknowledge for playing a role in data collection.

These match to DataCite (Zenodo) as follows:
curator = DataCurator
collector = DataCollector
contact = ContactPerson
assistants = RelatedPerson

And the link to the DataCite terminology should be included in the AusTraits definitions file.
```
people:
  collectors:
  - name: Ernst-Detlef Schulze
    institution: Max-Planck Institute for Biogeochemistry
  - name: Willi A. Brand
    institution: Max-Planck Institute for Biogeochemistry
  contact: Ernst-Detlef Schulze
  curator: Caitlan Baxter
  assistants: Inge Schulze, R.J.Williams, Waltraud Schulze
```

**Comment by ehwenk** [comment]
The DataCite-property for `institution` is `affiliation`. Maybe we should use this instead? 
https://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf

And name categories are: familyName, givenName - even if we don't go with camelCase, maybe, we switch to family_name?

**Comment by ehwenk** [comment]
@GaryTruong 

Daniel and I continued talking through possible formats for the contributors section. Below is an example of what we've settled on for the metadata.yml format.

In the output, austraits$methods will have columns for contributors (semicolon delimited list of names); assistants; curator; contact. We didn't actually discuss the changing the austraits$contributors format, but I wonder if it will change to just being the collectors' names and will include a column for ORCIDs.

```
contributors:
  collectors:
  - last_name: Caldwell
    given_name: Elizabeth 
    affiliation: School of Biological Sciences, Monash University
    additional_role: contact
  - last_name: Read
    given_name: Jennifer
    ORCID: 0000-0002-4727-3482
    affiliation: School of Biological Sciences, Monash University
  - last_name: Sanson
    given_name: Gordon
    affiliation: School of Biological Sciences, Monash University
  assistants: .na
  curator: Elizabeth Wenk
```
