### ISSUE TITLE
Add sampling date

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#361]
Several suggestions to record sampling date in main traits table. 

This carries on from #240 

I guess some studies will supply a year, others year-month, others, year-month-day
What resolution should we record?

We'll need to specific the column used for date. We may also need to do some transformations. We could either do this

1. in the custom R code, e.g.

```
custom_R_code: "data %>% mutate(date = dmy(date)"
```
or

2. We have a column in the config giving the format, e.g
```
config:
  data_is_long_format: yes
  variable_match:
    species_name: species_name
    trait_name: trait
    date_name: date
  date_format:  ymd
```

Preferences?
