### ISSUE TITLE
Rework context fields

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#506]
Currently the information contained in field under contexts is different for studies with a single contextual condition (i.e. sampling season) than for studies with multiple contextual conditions (i.e. sampling season and fire severity)

For studies with a single contextual condition, there are generally two fields, 'type' which identifies the 'type' of each contextual condition value and 'description' which explicitly describes the meaning of a single contextual condition value. (e.g. Bloomfield_2018).

For studies with multiple contextual conditions, the context names are the unique factorial combinations of contextual condition values pasted together (e.g. grown_at_high_CO2_under_drought_conditions vs. grown_at_low_CO2_under_drought_conditions). The fields for such studies would include 'type' (a combined type - or the most applicable type); 'description' (not very meaningful - usually simply indicating there are factorial combinations); 'CO2_concentration' (explicitly listing the relevant CO2 concentrations for each context name)[ and 'water treatment' (explicitly listing the relevant water treatment for the context name). 

For a single context study, there needs to be a field that names the contextual condition (e.g. 'growing season' or 'fire severity').

For a multiple context study, there needs to be a mechanism to indicate 'type' for each contextual condition. Also, for such studies, 'description' is meaningless, while the information keyed in under each contextual condition name (e.g. 'water treatment: Wet (well-watered seedlings were maintained at field capacity) is the equivalent to what is under 'description' for a single context study. 

I think the solution to this is to have separate sections titled 'contexts:' which is a context name (not changed), followed by a list of the contextual conditions for the study, each detailing the value (e.g. 'water treatment: wet'). Then below will be a second section titled 'contextual_conditions:' where each condition and its values are defined, including 'type'. 

Examples:

Single context example, Farrell_2013:
```
contexts:
- name: Water-deficit
  water_availability: Water-deficit
- name: Well-watered
  water_availability: Well-watered
contextual_conditions:
- condition: water_availability
  type: treatment
  values:
    Water-deficit: Plants were dried out to approximately 10% SWC before being rewatered to pot capacity and again left to dry out.
    Well-watered: Plants were watered twice weekly (Monday and Thursday) to pot capacity (2 L per pot).
```

Single contextual condition, Bloomfield_2018:
```
contexts:
- name: Dry
  season: Dry
- name: Summer_favourable
  season: Summer_favourable
- name:   Summer_unfavourable
  season: Summer_unfavourable
- name: Wet
  season: Wet
- name: Winter_favourable
  season: Winter_favourable
- name: Winter_unfavourable
  season: Winter_unfavourable
contextual_conditions:
- condition: season
  type: field
  values:
    Dry: sample collected during the dry season
    Summer_favourable: sample collected during the summer in a location where this is the favourable season
    Summer_unfavourable: sample collected during the summer in a location where this is the unfavourable season
    Wet: sample collected during the wet season
    Winter_favourable: sample collected during the winter in a location where this is the favourable season
    Winter_unfavourable: sample collected during the winter in a location where this is the unfavourable season
```

Multi-context example, Choat_2006:
```
contexts:
- name: measurements made in the Dry season at 05:00:00
  time: 05:00:00
  season: Dry (July-October)
- name: measurements made in the Dry season at 09:00:00
  time: 09:00:00
  season: Dry (July-October)
- name: measurements made in the Dry season at 11:00:00
  time: 11:00:00
  season: Dry (July-October)
- name: measurements made in the Dry season at 13:00:00
  time: 13:00:00
  season: Dry (July-October)
- name: measurements made in the Dry season at 15:00:00
  time: 15:00:00
  season: Dry (July-October)
- name: measurements made in the Late Dry season at 05:00:00
  time: 05:00:00
  season: Late Dry (September)
- name: measurements made in the Late Dry season at 10:00:00
  time: 10:00:00
  season: Late Dry (September)
- name: measurements made in the Late Dry season at 15:00:00
  time: 15:00:00
  season: Late Dry (September)
- name: measurements made in the Late Dry season at 18:00:00
  time: 18:00:00
  season: Late Dry (September)
- name: measurements made in the Wet season at 05:00:00
  time: 05:00:00
  season: Wet (November-March)
- name: measurements made in the Wet season at 09:00:00
  time: 09:00:00
  season: Wet (November-March)
- name: measurements made in the Wet season at 11:00:00
  time: 11:00:00
  season: Wet (November-March)
- name: measurements made in the Wet season at 13:00:00
  time: 13:00:00
  season: Wet (November-March)
- name: measurements made in the Wet season at 15:00:00
  time: 15:00:00
  season: Wet (November-March)
- name: measurements made in the Wet season at 17:00:00
  time: 17:00:00
  season: Wet (November-March)
- name: measurements made in the Wet/Dry season at 05:00:00
  time: 05:00:00
  season: Wet/Dry (April-June)
- name: measurements made in the Wet/Dry season at 09:00:00
  time: 09:00:00
  season: Wet/Dry (April-June)
- name: measurements made in the Wet/Dry season at 11:00:00
  time: 11:00:00
  season: Wet/Dry (April-June)
- name: measurements made in the Wet/Dry season at 13:00:00
  time: 13:00:00
  season: Wet/Dry (April-June)
- name: measurements made in the Wet/Dry season at 15:00:00
  time: 15:00:00
  season: Wet/Dry (April-June)
- name: measurements made in the Wet/Dry season at 17:00:00
  time: 17:00:00
  season: Wet/Dry (April-June)
- name: no context given
  time: .na.character
  season: .na.character
contextual_conditions:
- condition: time
  type: field
  values:
    05:00:00: measurements made at 05:00:00
    09:00:00: measurements made at 09:00:00
    10:00:00: measurements made at 10:00:00
    11:00:00: measurements made at 11:00:00
    13:00:00: measurements made at 13:00:00
    15:00:00: measurements made at 15:00:00
    17:00:00: measurements made at 17:00:00
    18:00:00: measurements made at 18:00:00
- condition: season
  type: field
  values:
    Dry (July-October): measurements made in the dry season (July-October)
    Late Dry (September): measurements made in the late dry season (September)
    Wet (November-March): measurements made in the wet season (November-March)
    Wet/Dry (April-June): measurements made at the boundary between the wet and dry seasons (April-June)
```

Multi-context example, Huang_2015:
```
contexts:
- name: Seeds_from_Coastal_population_grown_at_Amb_temp_and_400_ppm_CO2
  population: Coastal
  growing temperature: Ambient (26/18 deg C (day/night))
  growing CO2 (ppm): 400 (ambient)
- name: Seeds_from_Coastal_population_grown_at_Amb_temp_and_640_ppm_CO2
  population: Coastal
  growing temperature: Ambient (26/18 deg C (day/night))
  growing CO2 (ppm): 640 (elevated)
- name: Seeds_from_Coastal_population_grown_at_Elv_temp_and_400_ppm_CO2
  population: Coastal
  growing temperature: Elevated (30/22 deg C (day/night))
  growing CO2 (ppm): 400 (ambient)
- name: Seeds_from_Coastal_population_grown_at_Elv_temp_and_640_ppm_CO2
  population: Coastal
  growing temperature: Elevated (30/22 deg C (day/night))
  growing CO2 (ppm): 640 (elevated)
- name: Seeds_from_Upland_population_grown_at_Amb_temp_and_400_ppm_CO2
  population: Upland
  growing temperature: Ambient (26/18 deg C (day/night))
  growing CO2 (ppm): 400 (ambient)
- name: Seeds_from_Upland_population_grown_at_Amb_temp_and_640_ppm_CO2
  population: Upland
  growing temperature: Ambient (26/18 deg C (day/night))
  growing CO2 (ppm): 640 (elevated)
- name: Seeds_from_Upland_population_grown_at_Elv_temp_and_400_ppm_CO2
  population: Upland
  growing temperature: Elevated (30/22 deg C (day/night))
  growing CO2 (ppm): 400 (ambient)
- name: Seeds_from_Upland_population_grown_at_Elv_temp_and_640_ppm_CO2
  population: Upland
  growing temperature: Elevated (30/22 deg C (day/night))
  growing CO2 (ppm): 640 (elevated)
contextual_conditions:
- condition: population
  type: field
  values:
    Upland: Seeds collected from Newnes Forest, at 33.39 deg S, 150.21 deg E, 1150 m altitude
    Coastal: Seeds collected from Patonga, at 33.53 deg S, 151.28 deg E, 180 m altitude
- condition: growing temperature
  type: treatment
  values:
    Elevated (30/22 deg C (day/night)): Plants grown at elevated temperatures (30/22 deg C (day/night))
    Ambient (26/18 deg C (day/night)): Plants grown at ambient temperatures (26/18 deg C (day/night))
- condition: growing CO2 (ppm)
  type: treatment
  values:
    400 (ambient): Plants grown at ambient CO2 (400 ppm)
    640 (elevated): Plants grown at elevated CO2 (640 ppm)
```
