### ISSUE TITLE
Metadata_create_template doesn't add correct fields for contributors

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#715]
The function `metadata_create_template` doesn't correctly format the fields for data contributors.:

```
contributors:
  data_collectors:
  - elements: unknown
  assistants: unknown
  austraits_curators: unknown
```

We're been copying and pasting across the fields from other studies.
